runtime/build.gradle.kts
runtime/src/jvmTest/kotlin/kotlinx/rpc/test/api/ApiTestContext.kt
runtime/src/jvmTest/kotlin/kotlinx/rpc/test/api/ApiVersioningTest.kt
runtime/src/jvmTest/kotlin/kotlinx/rpc/test/api/IndexedEnumTest.kt
runtime/src/jvmTest/kotlin/kotlinx/rpc/test/api/WireSamplingTestScope.kt
runtime/src/jvmTest/kotlin/kotlinx/rpc/test/api/util/GoldChecks.kt

- If version of the library changes, but tracked API did not - do not fail tests
- Replace script generation with a Gradle task for updating gold files

Relax API Versioning test

---

CONTRIBUTING.md
docs/pages/kotlinx-rpc/cfg/buildprofiles.xml
docs/pages/kotlinx-rpc/v.list

- Updated broken links on the docs website
- Updated contribution guide to include the docs website

Updated links on the docs website

---

bom/build.gradle.kts
gradle-conventions/build.gradle.kts
gradle-conventions/gradle-publish-stub/build.gradle.kts
gradle-conventions/gradle-publish-stub/src/main/kotlin/conventions-gradle-publish.gradle.kts
gradle-conventions/gradle-publish/build.gradle.kts
gradle-conventions/gradle-publish/src/main/kotlin/conventions-gradle-publish.gradle.kts
gradle-conventions/settings.gradle.kts
gradle-conventions/src/main/kotlin/conventions-common.gradle.kts
gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
gradle-conventions/src/main/kotlin/util/PublicationUtils.kt
gradle-plugin/build.gradle.kts
gradle-plugin/gradle-plugin-all/build.gradle.kts
gradle-plugin/gradle-plugin-platform/build.gradle.kts
gradle-settings-conventions/src/main/kotlin/settings-conventions.settings.gradle.kts
gradle/libs.versions.toml

Added configs for artifacts signing and configuration for Sonatype and Gradle Plugin Portal publications

Signing and Publication

---

.github/workflows/build-docs.yml
docs/pages/kotlinx-rpc/cfg/buildprofiles.xml

Writerside supports search, for that we can use Algolia
https://www.jetbrains.com/help/writerside/deploy-docs-to-github-pages.html#search

Added search indexes publication to Algolia action

---

.idea/vcs.xml

No links in IDEA coomit list
**Solution**
Add IDEA VCS configuration

IDEA. Issue links

---

.github/workflows/build-test-docs.yml
.github/workflows/deploy-docs.yml
docs/pages/kotlinx-rpc/topics/transport.topic

Docs changes were not tested on PR, which can lead to a broken build in `main`
Also fixed this broken build

Added build and test docs on PR

---

.github/workflows/docs.yml

**Subsystem**
Docs website
Documentation gets updated ahead of releases
**Solution**
Disable autoupdate, update manually on release

Disable docs website autoupdate

---

README.md
docs/pages/kotlinx-rpc/topics/get-started.topic
docs/pages/kotlinx-rpc/topics/plugins.topic
docs/pages/kotlinx-rpc/topics/releases.topic

**Subsystem**
Documentation
Docs are outdated due to https://github.com/Kotlin/kotlinx-rpc/pulls?q=is:pr+is:closed
**Solution**
UPdate docs to match the current state

KRPC-60 Update docs to match the new versioning scheme

---

README.md
docs/pages/kotlinx-rpc/topics/get-started.topic
docs/pages/kotlinx-rpc/topics/plugins.topic
docs/pages/kotlinx-rpc/topics/releases.topic

**Subsystem**
Docs
**Solution**
Update docs to use new artifact names and repository configurations

Update docs for new artifacts and repositories

---

README.md
docs/pages/kotlinx-rpc/rpc.tree
docs/pages/kotlinx-rpc/topics/0-2-0.topic
docs/pages/kotlinx-rpc/topics/get-started.topic
docs/pages/kotlinx-rpc/topics/versions.topic

**Subsystem**
Docs
0.2.0 contains a lot of incompatibilities
**Solution**
Provide migration guide for users

Migration guide for 0.2.0

---

README.md
docs/pages/kotlinx-rpc/rpc.tree
docs/pages/kotlinx-rpc/topics/0-2-0.topic
docs/pages/kotlinx-rpc/topics/get-started.topic
docs/pages/kotlinx-rpc/topics/plugins.topic
docs/pages/kotlinx-rpc/topics/releases.topic
docs/pages/kotlinx-rpc/topics/versions.topic

A branch with accumulated changed for 0.2.0 release, that are not in `main`

Release 0.2.0 - Draft Changes

---

gradle-conventions/conventions-utils/src/main/kotlin/util/PublicationUtils.kt
gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
gradle-settings-conventions/src/main/kotlin/includePublic.kt
settings.gradle.kts

**Subsystem**
Gradle build
Some artifacts lacked kotlinx-rpc- prefix in Gradle metadata files.
**Solution**
Fix the metadata manually

Fix publication artifacts

---

kotlin-js-store/yarn.lock

**Subsystem**
K/JS target
Kotlin 2.0 updated internal yarn deps
**Solution**
Update `yarn.lock`. The update is big, so splitted into a separate PR

yarn.lock update for 2.0

---

ksp-plugin/src/main/kotlin/kotlinx/rpc/codegen/RPCClientServiceGenerator.kt

**Subsystem**
KSP Plugin
Root imports are not distinct
**Solution**
Make them distinct by the name

Conflicting imports for root classes

---

core/src/commonMain/kotlin/kotlinx/rpc/internal/ExceptionUtils.kt
core/src/commonMain/kotlin/kotlinx/rpc/internal/ReflectionUtils.kt
core/src/jsMain/kotlin/kotlinx/rpc/internal/ReflectionUtils.js.kt
core/src/jvmMain/kotlin/kotlinx/rpc/internal/ExceptionUtils.jvm.kt
core/src/jvmMain/kotlin/kotlinx/rpc/internal/ReflectionUtils.jvm.kt
core/src/nativeMain/kotlin/kotlinx/rpc/internal/ReflectionUtils.native.kt
gradle-conventions-settings/src/main/kotlin/util/PublicationUtils.kt
krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/test/KRPCTestService.kt
krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/test/KRPCTestServiceBackend.kt
krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/test/KRPCTransportTestBase.kt
publishLocal.sh

**Subsystem**
Core
Exceptions with message and cause are not deserialized properly 
**Solution**
- Fix constructor choosing when deserializing
- Fix field counting

Exception Deserialization

---

docs/pages/kotlinx-rpc/topics/0-2-4.topic
samples/ktor-android-app/README.md

Some wording fixes that I found

Wording fixes

---

.idea/codeStyles/codeStyleConfig.xml
.idea/vcs.xml

**Subsystem**
.idea directory
No problem
**Solution**
Added KRPC internal tracker mappings

Update some ide configs

---

build.gradle.kts
compiler-plugin/build.gradle.kts
gradle-conventions/latest-only/build.gradle.kts
gradle-conventions/latest-only/src/main/kotlin/conventions-gradle-doctor.gradle.kts
gradle-plugin/build.gradle.kts
versions-root/libs.versions.toml

**Subsystem**
Gradle
Some project configurations may lead to unexpected overhead
**Solution**
Added Gradle Doctor plugin to maintain stability

Added Gradle Doctor to the build

---

.gitignore
compiler-plugin/settings.gradle.kts
docs/develocity.md
gradle-conventions-settings/develocity/build.gradle.kts
gradle-conventions-settings/develocity/src/main/kotlin/conventions-develocity.settings.gradle.kts
gradle-conventions-settings/develocity/src/main/kotlin/customization.kt
gradle-conventions-settings/develocity/src/main/kotlin/execute.kt
gradle-conventions-settings/develocity/src/main/kotlin/params.kt
gradle-conventions-settings/settings.gradle.kts
gradle.properties
ksp-plugin/settings.gradle.kts
settings.gradle.kts

**Subsystem**
Gradle
**Solution**
Added Develocity build cache and scans

Added build cache and develocity plugin

---

compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/VersionSpecificApi.kt
compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RPCStubGenerator.kt
compiler-plugin/compiler-plugin-backend/src/main/pre_2_0_10/kotlinx/rpc/codegen/VersionSpecificApiImpl.kt
compiler-plugin/compiler-plugin-backend/src/main/pre_2_0_21/kotlinx/rpc/codegen/VersionSpecificApiImpl.kt
compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcSupertypeGeneratorAbstract.kt
compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcUtils.kt
compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirVersionSpecificApi.kt
compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/serialization/annotation.kt
compiler-plugin/compiler-plugin-k2/src/main/latest/kotlinx/rpc/codegen/FirRpcSupertypeGenerator.kt
compiler-plugin/compiler-plugin-k2/src/main/latest/kotlinx/rpc/codegen/FirVersionSpecificApiImpl.kt
compiler-plugin/compiler-plugin-k2/src/main/pre_2_0_10/kotlinx/rpc/codegen/FirRpcSupertypeGenerator.kt
compiler-plugin/compiler-plugin-k2/src/main/pre_2_0_21/kotlinx/rpc/codegen/FirRpcSupertypeGenerator.kt
compiler-plugin/compiler-plugin-k2/src/main/pre_2_0_21/kotlinx/rpc/codegen/FirVersionSpecificApiImpl.kt
gradle-conventions-settings/src/main/kotlin/conventions-repositories.settings.gradle.kts
krpc/krpc-test/build.gradle.kts
versions-root/libs.versions.toml

**Subsystem**
Kotlin `2.1.0-RC` is out with breaking changes in Compiler API
**Solution**
Update and fix changes

Support Kotlin 2.1.0-RC2

---

compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/VersionSpecificApi.kt
compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RpcStubGenerator.kt

**Subsystem**
Latest Kotlin master does not compile with the lib
**Solution**
Fix error compilation error

Fix Kotlin master compilation

---

gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts

**Subsystem**
Gradle
We now will release dev versions of grpc
**Solution**
Add release repo link

Added grpc release repo

---

renovate.json5

**Subsystem**
Renovate
Renovate spams with PRs
**Solution**
Update Renovate Configs

Added python deps automerge

---

protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ProtoToModelInterpreter.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/RpcProtobufPlugin.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/FieldDeclaration.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/FileDeclaration.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/FqName.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/MessageDeclaration.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/MethodDeclaration.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/NameResolver.kt
protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/FqNameTest.kt
protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/NameResolverTest.kt
protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/TestReferenceService.kt
protobuf-plugin/src/test/proto/reference.proto
protobuf-plugin/src/test/proto/reference_package.proto
protobuf-plugin/src/test/proto/reference_service.proto

**Subsystem**
Protobuf Plugin
Reference types in messages were not supported
**Solution**
Support them in two steps:
- Add proper FQ name resolution
- Support codegen with Reference types

gRPC Reference Types

---

protobuf-plugin/build.gradle.kts
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ProtoToModelInterpreter.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/EnumDeclaration.kt
protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/TestReferenceService.kt
protobuf-plugin/src/test/proto/enum.proto
protobuf-plugin/src/test/proto/enum_options.proto
protobuf-plugin/src/test/proto/reference_service.proto

**Subsystem**
gRPC, Protobuf plugin
**Solution**
Support Enum types

KRPC-141 Enum support in gRPC

---

protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/CodeGenerator.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ProtoToModelInterpreter.kt
protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/TestReferenceService.kt
protobuf-plugin/src/test/proto/optional.proto
protobuf-plugin/src/test/proto/reference_service.proto

**Subsystem**
gRPC, Protobuf Plugin
**Solution**
Support Optional Types as Kotlin nullables

KRPC-142 gRPC Optional Types Support

---

gradle-conventions/common/src/main/kotlin/util/apiValidation.kt

Fix api check

---

samples/ktor-all-platforms-app/composeApp/build.gradle.kts
samples/ktor-all-platforms-app/composeApp/src/commonMain/kotlin/App.kt
samples/ktor-all-platforms-app/gradle/libs.versions.toml
samples/ktor-all-platforms-app/server/build.gradle.kts
samples/ktor-all-platforms-app/server/src/main/kotlin/kotlinx/rpc/sample/UserServiceImpl.kt
samples/ktor-all-platforms-app/server/src/test/kotlin/kotlinx/rpc/sample/ApplicationTest.kt
samples/ktor-all-platforms-app/shared/src/commonMain/kotlin/UserService.kt
samples/ktor-android-app/app/build.gradle.kts
samples/ktor-android-app/app/src/main/kotlin/kotlinx/rpc/sample/ui/AppViewModel.kt
samples/ktor-android-app/common/src/main/kotlin/kotlinx/rpc/sample/MyService.kt
samples/ktor-android-app/gradle/libs.versions.toml
samples/ktor-android-app/server/build.gradle.kts
samples/ktor-android-app/server/src/main/kotlin/kotlinx/rpc/sample/MyServiceImpl.kt
samples/ktor-android-app/server/src/test/kotlin/ApplicationTest.kt
samples/ktor-web-app/common/src/commonMain/kotlin/Common.kt
samples/ktor-web-app/frontend/build.gradle.kts
samples/ktor-web-app/frontend/src/jsMain/kotlin/App.kt
samples/ktor-web-app/frontend/src/jsMain/kotlin/Welcome.kt
samples/ktor-web-app/gradle/libs.versions.toml
samples/ktor-web-app/server/build.gradle.kts
samples/ktor-web-app/server/src/main/kotlin/MyServiceImpl.kt
samples/ktor-web-app/server/src/test/kotlin/ApplicationTest.kt
samples/simple-ktor-app/build.gradle.kts
samples/simple-ktor-app/src/main/kotlin/Client.kt
samples/simple-ktor-app/src/main/kotlin/ImageRecognizer.kt
samples/simple-ktor-app/src/test/kotlin/ApplicationTest.kt

**Subsystem**
Samples
Routine update to `0.6.1`

Update samples to 0.6.1

---

.github/workflows/docs.yml
README.md
docs/pages/kotlinx-rpc/help-versions.json
docs/pages/kotlinx-rpc/v.list
docs/pages/kotlinx-rpc/writerside.cfg
versions-root/libs.versions.toml

**Subsystem**
Docs
Forgot to update version in docs
**Solution**
Update it

Update version to 0.6.1 in docs

---

.github/workflows/docs.yml
CHANGELOG.md
README.md
docs/pages/kotlinx-rpc/help-versions.json
docs/pages/kotlinx-rpc/v.list
docs/pages/kotlinx-rpc/writerside.cfg
versions-root/libs.versions.toml

Release `0.6.2` with a bugfix for Unit flows

Release 0.6.2

---

versions-root/libs.versions.toml

Version 0.7.0-SNAPSHOT

---

samples/ktor-all-platforms-app/gradle/libs.versions.toml
samples/ktor-android-app/gradle/libs.versions.toml
samples/ktor-web-app/gradle/libs.versions.toml
samples/simple-ktor-app/build.gradle.kts

**Subsystem**
Samples
**Solution**
Updated samples version to `0.6.2`

Samples: version 0.6.2

---

docs/pages/kotlinx-rpc/topics/grpc-configuration.topic

**Subsystem**
Docs
Docs for #402

Add a doc for KMP source sets with gRPC

---

README.md
compiler-plugin/compiler-plugin-k2/src/main/templates/kotlinx/rpc/codegen/FirVersionSpecificApiImpl.kt
docs/pages/kotlinx-rpc/topics/versions.topic
docs/pages/kotlinx-rpc/v.list
kotlin-js-store/package-lock.json
kotlin-js-store/wasm/package-lock.json
versions-root/libs.versions.toml

**Subsystem**
Compiler plugin, Versions
2.2.10 is out
**Solution**
- Support 2.2.10
- Fix Kotlin Master builds

Kotlin 2.2.10
