Kotlin/kotlinx-rpc

- ksp-plugin/src/main/kotlin/kotlinx/rpc/codegen/CodeWriter.kt
- ksp-plugin/src/main/kotlin/kotlinx/rpc/codegen/RPCClientServiceGenerator.kt
**Subsystem**
KSP plugin.
The code in `RPCClientServiceGenerator` would be easier to follow if it had no duplicated `write` and `newLine` methods which always go together.
**Solution**
Introduce `fun CodeWriter.writeLine(str: String)` which does writing given text and a newline character.
Since all the `write` method usages are followed by the `newLine` method call, the code becomes easier to read.
As a bonus, the `write` method is not used anymore and can be removed.
The changes in this commit do not change the file being written except for the final newline character.
Previously, generated files did not contain a newline character, and now they will.
> Replace consequent `write` and `newLine` calls on CodeWriter with `writeLine`

- runtime/api/kotlinx-rpc-runtime.api
- runtime/runtime-client/src/commonMain/kotlin/kotlinx/rpc/client/KRPCClient.kt
- runtime/src/commonMain/kotlin/kotlinx/rpc/internal/RPCStreamContext.kt
- runtime/src/commonMain/kotlin/kotlinx/rpc/internal/ServiceScope.kt
- runtime/src/commonMain/kotlin/kotlinx/rpc/internal/devStreamScope.kt
- runtime/src/commonMain/kotlin/kotlinx/rpc/internal/scopedClientCall.kt
- runtime/src/jvmTest/kotlin/kotlinx/rpc/test/cancellation/CancellationTest.kt
Some of our internal users rely on absence of `StreamScope`s
This PR adds ability to provide release with relaxed rules for stream API, but toggling one parameter
> Add dev mode toggle for stream scope for internal use

- docs/pages/kotlinx-rpc/topics/transport.topic
- transport/transport-ktor/src/jvmTest/kotlin/kotlinx/rpc/transport/ktor/KtorTransportTest.kt
- transport/transport-ktor/transport-ktor-client/api/transport-ktor-client.api
- transport/transport-ktor/transport-ktor-client/src/commonMain/kotlin/kotlinx/rpc/transport/ktor/client/KtorClientDsl.kt
- transport/transport-ktor/transport-ktor-client/src/commonMain/kotlin/kotlinx/rpc/transport/ktor/client/KtorRPCClient.kt
**Subsystem**
Ktor integration, Client
Users can not access `WebSocketSession` that created RPC connection on client side
**Solution**
Expose `webSocketSession` property
> KRPC-62 WebSocketSession KtorRPCClient

- core/src/commonMain/kotlin/kotlinx/rpc/internal/RPCStreamContext.kt
**Subsystem**
Stream cancellation
There might be a race condition between `StreamEnd` and `StreamCancel` messages, resulting in a deadlock in 
```kotlin
public suspend fun cancelStream(message: RPCCallMessage.StreamCancel) {
incomingChannelOf(message.streamId).send(StreamCancel(message.cause.deserialize()))
}
```
`incomingChannelOf` waits for the cannel that was already removed and will never be present
**Solution**
Added a `closedStreams` set that checks for such already closed streams and if on is closed - does not wait to close it once again
> KRPC-97 Race condition in stream cancellation locks the transport

- core/api/core.api
- core/src/commonMain/kotlin/kotlinx/rpc/RPCTransport.kt
- core/src/commonMain/kotlin/kotlinx/rpc/internal/scopedClientCall.kt
- core/src/commonMain/kotlin/kotlinx/rpc/internal/transport/RPCConnector.kt
- gradle/libs.versions.toml
- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/client/KRPCClient.kt
- krpc/krpc-ktor/krpc-ktor-core/build.gradle.kts
- krpc/krpc-ktor/krpc-ktor-core/src/commonMain/kotlin/kotlinx/rpc/transport/ktor/KtorTransport.kt
- krpc/krpc-ktor/krpc-ktor-core/src/jvmTest/kotlin/kotlinx/rpc/transport/ktor/KtorTransportTest.kt
- krpc/krpc-test/build.gradle.kts
- krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/test/cancellation/CancellationService.kt
- krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/test/cancellation/CancellationTest.kt
**Subsystem**
kRPC protocol
- Requests do not cancel on service/client cancellation
- Transport cancels abruptly in Ktor resulting in error messages in log
**Solution**
- Handle service/client cancellation case
- Return null in `RPCTransport` receive when messages ended
> Fix call cancellation

- docs/pages/kotlinx-rpc/topics/plugins.topic
**Subsystem**
Docs
Outdated configuration documentation
**Solution**
Update docs to match configs with K2
> Update docs for K2

- core/src/commonMain/kotlin/kotlinx/rpc/internal/RPCStreamContext.kt
In such case, the incomingChannels get cleared and closedStreams don't contain the streamId which leads to deadlock
> KRPC-101 Check if the entire stream is not already closed.

- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RPCStubGenerator.kt
**Subsystem**
Compiler plugin
Compilation on Kotlin/Native targets produces wrong IR, leading to 
```
kotlinx.serialization.SerializationException: Serializer for class 'rpcMethod' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
To get enum serializer on Kotlin/Native, it should be annotated with @Serializable annotation.
To get interface serializer on Kotlin/Native, use PolymorphicSerializer() constructor function.
```
**Solution**
Remove supertype overriding for `rpcMethod` classes, fixing the issue
> Fix compilation on Kotlin/Native

- tests/compiler-plugin-tests/src/testData/box/customParameterTypes.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/flowParameter.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/multiModule.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/simple.fir.ir.txt
**Subsystem**
Compiler plugin
Tests were not updated after previous change
**Solution**
Update tests
> Fix compiler tests after #172

- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RPCDeclarationScanner.kt
- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RPCIrServiceProcessor.kt
**Subsystem**
Compiler plugin
We introduced regression in patch release `0.2.4` that breaks compilation in case of nested declarations in RPC interfaces
**Solution**
Switch the error to a warning
> Fix regression of nested declarations in RPC interfaces

- samples/ktor-all-platforms-app/composeApp/src/commonMain/kotlin/App.kt
**Subsystem**
sample module
This PR addresses the removal of unused and inactive annotations in the sample module, specifically `@ExperimentalResourceApi`. The related import import `org.jetbrains.compose.resources.ExperimentalResourceApi` was also removed because it was no longer needed. This cleanup helps maintain code quality by removing unnecessary experimental annotations that are not being used in the current implementation.
**Solution**
Removed the `@ExperimentalResourceApi` annotation and its corresponding import `(import org.jetbrains.compose.resources.ExperimentalResourceApi)` from the sample module where it was inactive and not in use.
> Remove unused and inactive annotation

- core/src/jsMain/kotlin/kotlinx/rpc/internal/WithRPCStubObject.js.kt
**Subsystem**
Core
Overcomplicated way to access JsClass instance
**Solution**
Use stdlib
> Use built-in JsClass getter

- renovate.json
- renovate.json5
- versions-root/libs.versions.toml
**Subsystem**
Renovate
Renovate is noisy
**Solution**
Restrict scanning for some deps, group others
> Update renovate configs

- gradle-conventions-settings/src/main/kotlin/util/JsTarget.kt
- gradle-conventions-settings/src/main/kotlin/util/PublicationUtils.kt
- gradle-conventions-settings/src/main/kotlin/util/TargetUtils.kt
- gradle-conventions/src/main/kotlin/compiler-specific-module.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-kmp.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
- gradle-conventions/src/main/latest/util/wasm.kt
- tests/compiler-plugin-tests/build.gradle.kts
**Subsystem**
Gradle
Wasm artifacts were published without `kotlinx-rpc-` prefix
**Solution**
Add missing configs
> Fixed Wasm Publication

- docs/pages/kotlinx-rpc/rpc.tree
- docs/pages/kotlinx-rpc/topics/0-2-4.topic
- docs/pages/kotlinx-rpc/topics/0-3-0.topic
**Subsystem**
Documentation
0.3.0 release contains breaking changes
**Solution**
Describe changes with a migration path
> Migration guide for 0.3.0

- krpc/krpc-core/api/krpc-core.api
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/StreamScope.kt
- krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationTest.kt
**Subsystem**
kRPC
`streamScoped` function is not always usable, due to its strict lifetime limits
**Solution**
Provide `StreamScope` resource that is manageable via manual `close` calls.
> Experimental support for: KRPC-125 Manual stream scope management

- .gitignore
- build.gradle.kts
- compiler-plugin/settings.gradle.kts
- gradle-conventions-settings/build.gradle.kts
- gradle-conventions-settings/develocity/build.gradle.kts
- gradle-conventions-settings/settings.gradle.kts
- gradle-conventions-settings/src/main/kotlin/conventions-repositories.settings.gradle.kts
- gradle-conventions-settings/src/main/kotlin/conventions-version-resolution.settings.gradle.kts
- gradle-conventions-settings/src/main/kotlin/util/apiValidation.kt
- gradle-conventions-settings/src/main/kotlin/util/npm.kt
- gradle-conventions-settings/src/main/kotlin/util/projectReport.kt
- gradle-conventions-settings/src/main/kotlin/util/properties.kt
- gradle-conventions/settings.gradle.kts
- gradle-conventions/src/main/kotlin/compiler-specific-module.gradle.kts
- gradle-plugin/settings.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- kotlin-js-store/yarn.lock
- krpc/krpc-test/build.gradle.kts
- settings.gradle.kts
- tests/compiler-plugin-tests/build.gradle.kts
- versions-root/libs.versions.toml
**Subsystem**
Gradle
We used direct access for our package repositories, which may result in delays and throttling (and sometimes 500 codes, I'm looking at you npm)
**Solution**
Use proxy caching repositories
> Added proxy repository settings

- compiler-plugin/compiler-plugin-k2/build.gradle.kts
- gradle-conventions-settings/src/main/kotlin/conventions-version-resolution.settings.gradle.kts
- gradle-conventions-settings/src/main/kotlin/util/JsTarget.kt
- gradle-conventions-settings/src/main/kotlin/util/KotlinExtension.kt
- gradle-conventions-settings/src/main/kotlin/util/TargetUtils.kt
- gradle-conventions-settings/src/main/kotlin/util/forIde.kt
- gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
- gradle-conventions/src/main/latest/util/wasm.kt
- gradle.properties
- tests/compiler-plugin-tests/build.gradle.kts
- versions-root/libs.versions.toml
**Subsystem**
Gradle
We want to build `for-ide` compiler artifacts
**Solution**
Various infra changes that allow building such artifacts
> Added Kotlin for ide configs to project

- core/src/commonMain/kotlin/kotlinx/rpc/annotations/Rpc.kt
**Subsystem**
Core
Annoying warning for `@Rpc` in Kotlin/JS
**Solution**
Fix as in `kotlinx.serialization`
> Fix for KT-41082

- build.gradle.kts
- compiler-plugin/build.gradle.kts
- gradle-conventions-settings/src/main/kotlin/conventions-version-resolution.settings.gradle.kts
**Subsystem**
Gradle
Using LIBRARY_VERSION and EAP_VERSION env vars breaks version formatting
**Solution**
Fix it :)
> Fixed version formatting with ENV vars

- .github/workflows/labels.yml
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
- krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/krpc/test/LocalTransportTest.kt
**Subsystem**
Core
No problem
**Solution**
Add a test for a `@Contextual` use-case, #89
> Added test for non-serializable params

- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RpcIrContext.kt
- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RpcStubGenerator.kt
- core/api/core.api
- core/src/commonMain/kotlin/kotlinx/rpc/descriptor/RpcServiceDescriptor.kt
- gradle-conventions/latest-only/src/main/kotlin/conventions-gradle-doctor.gradle.kts
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/SerializationUtils.kt
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
- tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/BoxTestGenerated.java
- tests/compiler-plugin-tests/src/testData/box/customParameterTypes.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/fields.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/flowParameter.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/multiModule.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/simple.fir.ir.txt
**Subsystem**
Core
KType maybe changes in the future to KClass or custom metadata
**Solution**
Introduce intermediate `RpcType`
> Updated descriptor to use `RpcType` instead of `KType` directly

- README.md
- compiler-plugin/compiler-plugin-k2/src/main/latest/kotlinx/rpc/codegen/FirVersionSpecificApiImpl.kt
- docs/pages/kotlinx-rpc/topics/versions.topic
- docs/pages/kotlinx-rpc/v.list
- kotlin-js-store/yarn.lock
- versions-root/kotlin-versions-lookup.csv
- versions-root/libs.versions.toml
**Subsystem**
Infra
**Solution**
Support Kotlin 2.1.0
> Kotlin 2.1.0

- compiler-plugin/compiler-plugin-cli/src/main/latest/kotlinx/rpc/codegen/RpcCompilerPlugin.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcAdditionalCheckers.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcExtensionRegistrar.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/RpcFirCliOptions.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/FirCheckedAnnotationCheckers.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/Extensions.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/RpcDangerousApi.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/compilerPlugins.kt
- tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/services/ExtensionRegistrarConfigurator.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/checkedAnnotation.fir.txt
- tests/compiler-plugin-tests/src/testData/diagnostics/checkedAnnotation.kt
**Subsystem**
Compiler Plugin, Gradle Plugin
In https://github.com/Kotlin/kotlinx-rpc/pull/240 we added annotation type-safety analysis.
This is an experimental feature with the first iteration analysis checker.
It may be so, that it is slow, memory hungry or plain wrong, so there should be a way to opt-out of it, until an issue is resolved
**Solution**
Added kill switch
> Opt-out from annotations type safety analysis

- core/src/commonMain/kotlin/kotlinx/rpc/RpcCall.kt
- core/src/commonMain/kotlin/kotlinx/rpc/RpcClient.kt
**Subsystem**
Core
When removing APIs, forgot to make deprecated typealiases
> Added missing aliases for migration

- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcPredicates.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/FirRpcAnnotationChecker.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
- tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/BoxTestGenerated.java
- tests/compiler-plugin-tests/src/test-gen/kotlinx/rpc/codegen/test/runners/DiagnosticTestGenerated.java
- tests/compiler-plugin-tests/src/testData/diagnostics/rpcChecked.kt
**Subsystem**
Checked Type Annotation support transitive annotations, but diagnostic failed for `@Rpc` annottaion.
**Solution**
Fix that diagnostic
> Fixed @Rpc annotation diagnostic

- build.gradle.kts
- compiler-plugin/build.gradle.kts
- compiler-plugin/compiler-plugin-k2/build.gradle.kts
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
- gradle-conventions-settings/src/main/kotlin/conventions-version-resolution.settings.gradle.kts
- gradle-conventions/common/src/main/kotlin/util/forIde.kt
- gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
- gradle-plugin/build.gradle.kts
**Subsystem**
Gradle
Some configs for IDE were fixed in release-0.5.0 branch after it was merged into main
**Solution**
Backport fixes
> Update for IDE configs

- compiler-plugin/compiler-plugin-backend/src/main/v_2_2/kotlinx/rpc/codegen/VersionSpecificApiImpl.kt
- gradle-conventions/common/src/main/kotlin/util/apiValidation.kt
- settings.gradle.kts
**Subsystem**
Kotlin Master introduced a breaking change
**Solution**
Adapt
> Fix kotlin master

- README.md
- docs/pages/kotlinx-rpc/rpc.tree
- docs/pages/kotlinx-rpc/topics/get-started.topic
- docs/pages/kotlinx-rpc/topics/ide-plugin.topic
- docs/pages/kotlinx-rpc/topics/plugins.topic
**Subsystem**
Docs
IDE plugin as released
**Solution**
Add docs about that
> Added IDE plugin docs

- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/Payloads.kt
**Subsystem**
Tests
From the project start date we hade some tests that used `println` instead of asserts
**Solution**
Introduce asserts and fix tests
> Fix println tests

- gradle-plugin/build.gradle.kts
- gradle-plugin/src/main/kotlin/kotlinx/rpc/Extensions.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/GrpcExtension.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/KotlinCompilerPluginBuilder.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/RpcDangerousApi.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/RpcGradlePlugin.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/RpcPluginConst.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/compilerPlugins.kt
- protobuf-plugin/build.gradle.kts
- versions-root/libs.versions.toml
**Subsystem**
gRPC Gradle
gRPC Gradle config is unnecessary complicated
**Solution**
Simplify it using our Gradle plugin
> Simplified grpc gradle config

- .github/workflows/docs.yml
- CHANGELOG.md
- README.md
- docs/pages/kotlinx-rpc/help-versions.json
- docs/pages/kotlinx-rpc/topics/versions.topic
- docs/pages/kotlinx-rpc/v.list
- docs/pages/kotlinx-rpc/writerside.cfg
- krpc/krpc-test/src/jvmMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- samples/grpc-app/build.gradle.kts
- samples/ktor-all-platforms-app/gradle/libs.versions.toml
- samples/ktor-android-app/gradle/libs.versions.toml
- samples/ktor-web-app/gradle/libs.versions.toml
- samples/simple-ktor-app/build.gradle.kts
- versions-root/libs.versions.toml
Release 0.5.1
Mainly Kotlin Version update and some minor fixes
> Release 0.5.1

- compiler-plugin/compiler-plugin-backend/build.gradle.kts
- compiler-plugin/compiler-plugin-cli/build.gradle.kts
- compiler-plugin/compiler-plugin-common/build.gradle.kts
- compiler-plugin/compiler-plugin-k2/build.gradle.kts
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirRpcServiceGenerator.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/FirVersionSpecificApi.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
- gradle-conventions-settings/build.gradle.kts
- gradle-conventions-settings/develocity/build.gradle.kts
- gradle-conventions-settings/settings.gradle.kts
- gradle-conventions-settings/src/main/kotlin/conventions-version-resolution.settings.gradle.kts
- gradle-conventions-settings/src/main/kotlin/util/conventionsDefaults.kt
- gradle-conventions/src/main/kotlin/compiler-specific-module.gradle.kts
- tests/compiler-plugin-tests/build.gradle.kts
- versions-root/libs.versions.toml
**Subsystem**
Gradle
`for-ide` artifacts were built against wrong version of the compiler, which led to incompatibilities
**Solution**
Fix configs to build against proper compiler version, respecting `kotlin-compiler` param in `libs.versions.toml`
> Fix build config for for-ide builds

- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/CodeGenerator.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/RpcProtobufPlugin.kt
**Subsystem**
gRPC Protobuf plugin
Internal and public generated entities were placed into a single file, which complicates the comprehension of the content
**Solution**
Separate them into two files, placing internal declarations into the `_rpc_internal` subdirectory (but package is the same)
> KRPC-162 Internal vs Public Codegen separation in gRPC

- docs/pages/kotlinx-rpc/topics/grpc-configuration.topic
- samples/grpc-app/build.gradle.kts
**Subsystem**
gRPC Docs
gRPC just got a Gradle config update
**Solution**
Update docs and the sample
> Update gRPC Docs and Sample

- compiler-plugin/build.gradle.kts
- compiler-plugin/compiler-plugin-backend/build.gradle.kts
- compiler-plugin/compiler-plugin-cli/build.gradle.kts
- compiler-plugin/compiler-plugin-common/build.gradle.kts
- compiler-plugin/compiler-plugin-k2/build.gradle.kts
- versions-root/libs.versions.toml
**Subsystem**
Gradle
Custom Kotlin versions build (like 2.1.20-RC) that are NOT for IDE were misconfigured
**Solution**
Get rid of `embeddable` dependency which fixes the proper compiler version in builds
> Update build for custom KC versions

- krpc/krpc-test/build.gradle.kts
- settings.gradle.kts
- tests/krpc-compatibility-tests/build.gradle.kts
- tests/krpc-compatibility-tests/src/main/kotlin/kotlinx/rpc/krpc/compatibility/CompatibilityTest.kt
- tests/krpc-compatibility-tests/src/main/kotlin/kotlinx/rpc/krpc/compatibility/TestApiServer.kt
- tests/krpc-compatibility-tests/src/newApi/kotlin/interfaces/Bar.kt
- tests/krpc-compatibility-tests/src/newApi/kotlin/interfaces/Baz.kt
- tests/krpc-compatibility-tests/src/newApi/kotlin/interfaces/Foo.kt
- tests/krpc-compatibility-tests/src/newApi/kotlin/tests/ApiServer.kt
- tests/krpc-compatibility-tests/src/newApi/kotlin/tests/CompatibilityTests.kt
- tests/krpc-compatibility-tests/src/oldApi/kotlin/interfaces/Bar.kt
- tests/krpc-compatibility-tests/src/oldApi/kotlin/interfaces/Baz.kt
- tests/krpc-compatibility-tests/src/oldApi/kotlin/interfaces/Foo.kt
- tests/krpc-compatibility-tests/src/oldApi/kotlin/tests/ApiServer.kt
- tests/krpc-compatibility-tests/src/oldApi/kotlin/tests/CompatibilityTests.kt
- tests/krpc-compatibility-tests/src/test/kotlin/kotlinx/rpc/krpc/compatibility/KrpcCompatibilityTests.kt
- tests/krpc-compatibility-tests/src/test/kotlin/kotlinx/rpc/krpc/compatibility/LocalTransport.kt
- versions-root/libs.versions.toml
**Subsystem**
Tests
Toolbox has internally added good tests for the protocol compatibility
**Solution**
Add those tests in the main kxrpc repo for better protocol regression notices
> KRPC-129 Move compatibility tests from Toolbox to Kotlin RPC repo

- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/FirCheckedAnnotationCheckers.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
**Subsystem**
#288 Message for compilation error was a mess
**Solution**
Better message
> Better compiler error message for checked annotations

- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RpcIrExtension.kt
- compiler-plugin/compiler-plugin-backend/src/main/core/kotlinx/rpc/codegen/extension/RpcIrServiceProcessor.kt
- compiler-plugin/compiler-plugin-backend/src/main/latest/kotlinx/rpc/codegen/RpcIrServiceProcessorDelegate.kt
- compiler-plugin/compiler-plugin-backend/src/main/pre_2_0_10/kotlinx/rpc/codegen/RpcIrServiceProcessorDelegate.kt
- compiler-plugin/compiler-plugin-backend/src/main/pre_2_0_21/kotlinx/rpc/codegen/RpcIrServiceProcessorDelegate.kt
- compiler-plugin/compiler-plugin-backend/src/main/v_2_2/kotlinx/rpc/codegen/RpcIrServiceProcessorDelegate.kt
- gradle-conventions-settings/src/main/kotlin/conventions-version-resolution.settings.gradle.kts
- gradle-conventions/empty/src/main/kotlin/util/npm.kt
- gradle-conventions/latest-only/src/main/kotlin/util/npm.kt
**Subsystem**
Compiler Plugin, Gradle
> Fix kotlin master compilation

- README.md
- docs/pages/kotlinx-rpc/topics/versions.topic
- docs/pages/kotlinx-rpc/v.list
- tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/runners/AbstractBoxTest.kt
- tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/runners/AbstractDiagnosticTest.kt
- tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/runners/BaseTestRunner.kt
- tests/compiler-plugin-tests/src/testData/box/customParameterTypes.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/fields.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/fields.fir.txt
- tests/compiler-plugin-tests/src/testData/box/flowParameter.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/multiModule.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/simple.fir.ir.txt
- versions-root/kotlin-versions-lookup.csv
- versions-root/libs.versions.toml
> Kotlin 2.1.20

- .github/workflows/docs.yml
- CHANGELOG.md
- README.md
- docs/pages/kotlinx-rpc/help-versions.json
- docs/pages/kotlinx-rpc/rpc.tree
- docs/pages/kotlinx-rpc/topics/0-6-0.topic
- docs/pages/kotlinx-rpc/topics/features.topic
- docs/pages/kotlinx-rpc/topics/plugins.topic
- docs/pages/kotlinx-rpc/topics/strict-mode.topic
- docs/pages/kotlinx-rpc/v.list
- docs/pages/kotlinx-rpc/writerside.cfg
- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/StreamScope.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationTest.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/rpcService.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/strictMode.kt
Highlights:
- Kotlin 2.1.20
- Non-suspend server flows
> Release 0.6.0

- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
**Subsystem**
kRPC Client
Bidirectional streams fail in `0.6.0` in non-suspend flows
**Solution**
Fix serialization context
> Fix bidirectional flows in non-suspend streams

- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/KrpcServerService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
**Subsystem**
kRPC server
#315
**Solution**
Provision values for return type match
> Fix KRPC-173 (#315)

- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/KrpcServerService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
**Subsystem**
kRPC Server
Function like 
```kotlin
@Rpc
interface Service {
fun request(): Flow<Unit>
}
```
Would through an error
**Solution**
Fix condition that checks it.
> Fix flows that emit Units

- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ProtoToModelInterpreter.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/FieldDeclaration.kt
- protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/TestReferenceService.kt
- protobuf-plugin/src/test/proto/reference_service.proto
- protobuf-plugin/src/test/proto/repeated.proto
**Subsystem**
gRPC
**Solution**
Support for `repeated` types in the Protobuf plugin
> KRPC-143 Repeated types in gRPC

- protobuf-plugin/build.gradle.kts
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ProtoToModelInterpreter.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/FqName.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/MessageDeclaration.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/NameResolver.kt
- protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/TestReferenceService.kt
- protobuf-plugin/src/test/proto/nested.proto
- protobuf-plugin/src/test/proto/reference_service.proto
**Subsystem**
gRPC
Proto files support nesting of declarations
**Solution**
Provide support in code gen
> KRPC-146 Nested types in gRPC

- protobuf-plugin/build.gradle.kts
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/ProtoToModelInterpreter.kt
- protobuf-plugin/src/main/kotlin/kotlinx/rpc/protobuf/model/FieldDeclaration.kt
- protobuf-plugin/src/test/kotlin/kotlinx/rpc/protobuf/test/TestReferenceService.kt
- protobuf-plugin/src/test/proto/reference_service.proto
- protobuf-plugin/src/test/proto/test_map.proto
**Subsystem**
gRPC
Support Map types in gRPC
> KRPC-145 Map types in gRPC

- README.md
- docs/pages/kotlinx-rpc/topics/versions.topic
- docs/pages/kotlinx-rpc/v.list
- versions-root/kotlin-versions-lookup.csv
- versions-root/libs.versions.toml
> Update Kotlin to 2.1.21

- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/StrictMode.kt
- compiler-plugin/compiler-plugin-k2/src/main/core/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
- docs/pages/kotlinx-rpc/topics/strict-mode.topic
- gradle-plugin/src/main/kotlin/kotlinx/rpc/Extensions.kt
- krpc/krpc-client/build.gradle.kts
- krpc/krpc-core/build.gradle.kts
- krpc/krpc-test/build.gradle.kts
- tests/compiler-plugin-tests/src/test/kotlin/kotlinx/rpc/codegen/test/services/ExtensionRegistrarConfigurator.kt
**Subsystem**
Gradle Plugin, Compiler Plugin
Strict mode was introduced in `0.5.0` with `warning` level.
**Solution**
Change default reporting level to `error`, as in `0.8.0` the mode will be enforced irreversibly.
> Change strict mode to level ERROR by default

- .github/workflows/docs.yml
- CHANGELOG.md
- README.md
- docs/pages/kotlinx-rpc/help-versions.json
- docs/pages/kotlinx-rpc/v.list
- docs/pages/kotlinx-rpc/writerside.cfg
- samples/ktor-all-platforms-app/gradle/libs.versions.toml
- samples/ktor-android-app/gradle/libs.versions.toml
- samples/ktor-web-app/gradle/libs.versions.toml
- samples/simple-ktor-app/build.gradle.kts
- versions-root/libs.versions.toml
Routine release, no major changes.
Main goal: change strict mode to ERROR before `0.8.0`.
> Release 0.7.0

- README.md
**Subsystem**
Documentation
README was still using semantics that are obsolete since #299
**Solution**
Remove suspend keyword from RPC functions returning a flow in the documentation
> Update README.md to use non-suspend flows

- compiler-plugin/compiler-plugin-k2/build.gradle.kts
- gradle-conventions-settings/src/main/kotlin/util/KotlinVersionActions.kt
**Subsystem**
Gradle
The condition for `-Xcontext-parameters` was wrong, leading to failed build
**Solution**
Fix condition for the proper compiler version.
> Fix compilation for standalone k2 module

- krpc/krpc-client/api/krpc-client.api
- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-ktor/krpc-ktor-client/api/krpc-ktor-client.api
- krpc/krpc-ktor/krpc-ktor-client/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/client/KtorClientDsl.kt
- krpc/krpc-ktor/krpc-ktor-client/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/client/KtorRpcClient.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestClient.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/LocalTransportTest.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/ProtocolTestBase.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationToolkit.kt
- krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/krpc/test/api/WireSamplingTestScope.kt
- tests/compiler-plugin-tests/src/main/kotlin/kotlinx/rpc/codegen/test/TestRpcClient.kt
- tests/krpc-compatibility-tests/src/test/kotlin/kotlinx/rpc/krpc/compatibility/LocalTransport.kt
**Strict mode Migration**
A series of changes to simplify kRPC protocol
**Subsystem**
Krpc Ktor
Ktor Krpc client requires invokavion of `.rpc` method which is suspending. In some cases that might be bad UX.
**Solution**
Allow for a cold client creation
> Cold Ktor client

- core/src/commonMain/kotlin/kotlinx/rpc/RpcCall.kt
- core/src/commonMain/kotlin/kotlinx/rpc/RpcClient.kt
- core/src/commonMain/kotlin/kotlinx/rpc/RpcServer.kt
- core/src/commonMain/kotlin/kotlinx/rpc/annotations/CheckedTypeAnnotation.kt
- core/src/commonMain/kotlin/kotlinx/rpc/annotations/Rpc.kt
- core/src/commonMain/kotlin/kotlinx/rpc/withService.kt
- docs/pages/kotlinx-rpc/rpc.tree
- docs/pages/kotlinx-rpc/topics/0-8-0.topic
- docs/pages/kotlinx-rpc/topics/annotation-type-safety.topic
- docs/pages/kotlinx-rpc/topics/configuration.topic
- docs/pages/kotlinx-rpc/topics/features.topic
- docs/pages/kotlinx-rpc/topics/krpc-client.topic
- docs/pages/kotlinx-rpc/topics/krpc-ktor.topic
- docs/pages/kotlinx-rpc/topics/krpc-server.topic
- docs/pages/kotlinx-rpc/topics/plugins.topic
- docs/pages/kotlinx-rpc/topics/rpc-clients.topic
- docs/pages/kotlinx-rpc/topics/rpc-servers.topic
- docs/pages/kotlinx-rpc/topics/services.topic
- docs/pages/kotlinx-rpc/topics/strict-mode.topic
- docs/pages/kotlinx-rpc/topics/transport.topic
- docs/pages/kotlinx-rpc/topics/versions.topic
- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/KrpcConfig.kt
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/KrpcTransport.kt
- krpc/krpc-ktor/krpc-ktor-client/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/client/KtorClientDsl.kt
- krpc/krpc-ktor/krpc-ktor-client/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/client/KtorRpcClient.kt
- krpc/krpc-ktor/krpc-ktor-core/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/KtorTransport.kt
- krpc/krpc-ktor/krpc-ktor-server/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/server/KrpcRoute.kt
- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/KrpcServer.kt
**Strict mode Migration**
A series of changes to simplify kRPC protocol
**Subsystem**
Kdocs, documentation
A lot of changes in 0.8.0 make most of the docs outdated.
**Solution**
Update API docs, examples, documentation website, and provide a migration guide.
> Documentation update for 0.8.0

- docs/pages/kotlinx-rpc/topics/0-8-0.topic
- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-ktor/krpc-ktor-core/build.gradle.kts
- krpc/krpc-ktor/krpc-ktor-core/src/jvmTest/kotlin/kotlinx/rpc/krpc/ktor/KtorTransportTest.kt
- krpc/krpc-ktor/krpc-ktor-core/src/jvmTest/resources/logback.xml
- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/KrpcServer.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationService.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationTest.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationToolkit.kt
**Subsystem**
kRPC
Some tests are missing, some changes were left out by previous PRs
**Solution**
- Add test for client streams
- Add test for websocket cancellation (muted for now until https://github.com/ktorio/ktor/pull/4927)
- Remove unnecessary change for constructor parameters order in `InitializedKrpcClient`
- Added `close` and `awaitCompletion` for `KrpcClient` and `KrpcServer`
> Quick fixes and tests

- .github/workflows/changelog.yml
- .github/workflows/docs.yml
- .github/workflows/dokka.yml
- .github/workflows/platforms.yml
- .idea/kotlinx-rpc.iml
- compiler-plugin/gradle.properties
- docs/pages/.gitignore
- docs/pages/kotlinx-rpc/topics/changelog.md
- dokka-plugin/gradle.properties
- gradle-conventions/src/main/kotlin/conventions-dokka-spec.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-gradle-doctor.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-root.gradle.kts
- gradle-conventions/src/main/kotlin/util/other/dokkaUtil.kt
- gradle-conventions/src/main/kotlin/util/targets/jvm.kt
- gradle-plugin/gradle.properties
- gradle.properties
- renovate.json5
- settings.gradle.kts
- updateSitemap.sh
**Subsystem**
Gradle, GA
Docs publication has some drawbacks to it:
- Long
- Hard to test
**Solution**
- Separate dokka generation into TC configs
- Add 'assemble all' step for all docs
Other updates:
- Foojay version 1.0.0
- Allow `exclude.jvm` options
- Commit changelog from docs
- Automated changelog verification
- Fix updateSitemap.sh
- Update renovate to ignore develocity
> Ci updates

- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/KrpcServer.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/CoroutineContextPropagationTest.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/LocalTransport.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationToolkit.kt
- krpc/krpc-test/src/jvmTest/kotlin/kotlinx/rpc/krpc/test/api/WireSamplingTestScope.kt
Issue: https://github.com/Kotlin/kotlinx-rpc/issues/226
> Propagate transport coroutine context

- gradle-conventions/src/main/kotlin/conventions-dokka-spec.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-root.gradle.kts
- gradle-conventions/src/main/kotlin/util/dokka.kt
**Subsystem**
Dokka
`Back to Docs` button only worked on the root page
**Solution**
Make it work everywhere
> Fix dokka API button for all modules

- docs/pages/kotlinx-rpc/topics/grpc-server.topic
- docs/pages/kotlinx-rpc/topics/grpc-services.topic
> Update gRPC doc

- krpc/krpc-ktor/krpc-ktor-client/api/krpc-ktor-client.api
- krpc/krpc-ktor/krpc-ktor-client/api/krpc-ktor-client.klib.api
- krpc/krpc-ktor/krpc-ktor-client/src/commonMain/kotlin/kotlinx/rpc/krpc/ktor/client/KtorRpcClient.kt
**Subsystem**
kRPC
We had a weird inheritance chain in `KtorRpcClient`, which didn't reflect that it is `KrpcClient`, so there is no way to cal `close()`, for example, without casting
**Solution**
Fix it!
> Make KtorRpcClient inherit KrpcClient

- docs/pages/kotlinx-rpc/topics/platforms.topic
- grpc/grpc-core/api/grpc-core.api
- grpc/grpc-core/api/grpc-core.klib.api
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/GrpcClient.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/GrpcServer.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.kt
- grpc/grpc-core/src/jsMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.js.kt
- grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.jvm.kt
- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.native.kt
- grpc/grpc-core/src/wasmJsMain/kotlin/kotlinx/rpc/grpc/ManagedChannel.wasmJs.kt
- grpc/grpc-ktor-server-test/build.gradle.kts
- grpc/grpc-ktor-server-test/gradle.properties
- grpc/grpc-ktor-server-test/src/test/kotlin/kotlinx/rpc/grpc/ktor/server/test/TestServer.kt
- grpc/grpc-ktor-server-test/src/test/proto/ktor-test-service.proto
- grpc/grpc-ktor-server-test/src/test/resources/logback.xml
- grpc/grpc-ktor-server/api/grpc-ktor-server.api
- grpc/grpc-ktor-server/api/grpc-ktor-server.klib.api
- grpc/grpc-ktor-server/build.gradle.kts
- grpc/grpc-ktor-server/gradle.properties
- grpc/grpc-ktor-server/src/commonMain/kotlin/kotlinx/rpc/grpc/ktor/server/Server.kt
- settings.gradle.kts
**Subsystem**
gRPC
We want to have Ktor plugin for gRPC
**Solution**
First version of the plugin
> gRPC: Ktor Plugin

- .github/workflows/docs.yml
- CHANGELOG.md
- README.md
- docs/pages/kotlinx-rpc/help-versions.json
- docs/pages/kotlinx-rpc/topics/changelog.md
- docs/pages/kotlinx-rpc/v.list
- docs/pages/kotlinx-rpc/writerside.cfg
- kotlin-js-store/package-lock.json
- kotlin-js-store/wasm/package-lock.json
- samples/ktor-all-platforms-app/gradle/libs.versions.toml
- samples/ktor-android-app/gradle/libs.versions.toml
- samples/ktor-web-app/gradle/libs.versions.toml
- samples/simple-ktor-app/build.gradle.kts
- versions-root/libs.versions.toml
Successor to https://github.com/Kotlin/kotlinx-rpc/pull/399.
Initial release is closed due to the same metadata issue poorly fixed
Minor release due to a breaking change in https://github.com/Kotlin/kotlinx-rpc/pull/396
Also this release fixes the metadata problem during the publication for unresolved Apple and Windows targets. The issue was on TC, so no PR linked
> Release 0.9.1

- gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/BufGenerateTask.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/GenerateBufGenYaml.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/buf/tasks/GenerateBufYaml.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/grpc/DefaultGrpcExtension.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/proto/DefaultProtoSourceSet.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/proto/ProcessProtoFiles.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/proto/derictory.kt
- gradle-plugin/src/main/kotlin/kotlinx/rpc/util/files.kt
- kotlin-js-store/package-lock.json
- kotlin-js-store/wasm/package-lock.json
**Subsystem**
Gradle Plugin
We run into config cache problems because of some bad inputs for tasks
**Solution**
Hopefully fix it
> Tasks caching

- grpc/grpc-core/build.gradle.kts
- grpc/grpc-core/gradle.properties
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/WireDecoder.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/WireEncoder.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.kt
- grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/internal/WireCodecTest.kt
- grpc/grpc-core/src/jsMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.js.kt
- grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/WireDecoder.jvm.kt
- grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/WireEncoder.jvm.kt
- grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/WireSize.jvm.kt
- grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.jvm.kt
- grpc/grpc-core/src/jvmTest/kotlin/kotlinx/rpc/grpc/core/test/TestReferenceService.kt
- grpc/grpc-core/src/jvmTest/proto/repeated.proto
- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/WireDecoder.native.kt
- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/WireEncoder.native.kt
- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.native.kt
- grpc/grpc-core/src/nativeTest/kotlin/kotlinx/rpc/grpc/internal/WireCodecTest.native.kt
- grpc/grpc-core/src/wasmJsMain/kotlin/kotlinx/rpc/grpc/internal/readPacked.wasmJs.kt
- grpc/grpc-ktor-server/gradle.properties
- protoc-gen/src/main/kotlin/kotlinx/rpc/protobuf/ModelToKotlinGenerator.kt
**Subsystem**
gRPC
We had codecs for K/N but not for jvm
**Solution**
Add them for jvm (and fix some issues along the way)
> Added jvm codecs implementations

- gradle-conventions/build.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-kotlin-version.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
- gradle-conventions/src/main/kotlin/conventions-root.gradle.kts
- gradle-plugin/build.gradle.kts
**Subsystem**
Gradle
- Fix `publishMavenPublication` tasks
- Fix LV version in GP
> Fix how we create 'publishMavenArtifact' tasks

- gradle-conventions/src/main/kotlin/conventions-publishing.gradle.kts
- krpc/krpc-test/build.gradle.kts
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
**Subsystem**
Gradle
So previous tinkering broke some things:
- Signing tasks are not that easy to properly configure one by one, so I rolled back
- LV version wasn't working previously at all, and now brought so compilation issues
> Fix LV and signing

- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/ServerStreamContext.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
**Subsystem**
kRPC
Client flows have side effects and thus can't be collected more than once
> Add collect once check for client streams

- compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/FirRpcExtensionRegistrar.kt
- compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/diagnostics/FirRpcDiagnostics.kt
- compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/diagnostics/RpcDiagnosticRendererFactory.kt
- compiler-plugin/compiler-plugin-k2/src/main/templates/kotlinx/rpc/codegen/checkers/diagnostics/RpcKtDiagnosticsContainer.kt
**Subsystem**
One of the previous refactoring broke rendering for diagnostics
> Fix diagnostic rendering for compiler plugins checkers

- versions-root/libs.versions.toml
This is a PR on a [PR](https://github.com/Kotlin/kotlinx-rpc/pull/438).
Just confirming it's working with [latest version](https://github.com/GradleUp/compat-patrouille/releases/tag/v0.0.1). 
Feel free to merge or discard this.
> Bump compat-patrouille version

- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestService.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTestServiceBackend.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/KrpcTransportTestBase.kt
- krpc/krpc-test/src/commonMain/kotlin/kotlinx/rpc/krpc/test/TestClass.kt
I encountered an issue where an RPC service returned null even though the RPC function never actually returns null
After investigation, it turned out that the error occurred during the deserialization of the server's response. However, kotlinx-rpc silently ignored the deserialization exception and performed an unchecked cast of null to the RPC function's return type T
This happens inside the KrpcClient class in the handleServerStreamingMessage function:
```Kotlin
is KrpcCallMessage.CallSuccess, is KrpcCallMessage.StreamMessage -> {
val value = runCatching {
val serializerResult = serialFormat.serializersModule
.buildContextual(callable.returnType)
decodeMessageData(serialFormat, serializerResult, message)
}
@Suppress("UNCHECKED_CAST")
channel.send(value.getOrNull() …
```
> fix wrong unchecked null cast (potential NPE)

- .setup_protoscope.sh
- docs/environment.md
- gradle-conventions/src/main/kotlin/util/other/localProperties.kt
- gradle-conventions/src/main/kotlin/util/tasks/protobufConformanceUpdate.kt
- tests/protobuf-conformance/build.gradle.kts
- tests/protobuf-conformance/src/main/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceClient.kt
- tests/protobuf-conformance/src/main/kotlin/kotlinx/rpc/protoc/gen/test/RunConformanceTest.kt
- tests/protobuf-conformance/src/main/kotlin/kotlinx/rpc/protoc/gen/test/runner/javaClient.kt
- tests/protobuf-conformance/src/main/kotlin/kotlinx/rpc/protoc/gen/test/runner/runner.kt
- tests/protobuf-conformance/src/test/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceTest.kt
**Subsystem**
Tests, Protobuf Conformance
Tests fail, but it is hard to debug them
**Solution**
Added the `protoscope` ulility integrated into the manual testing process, see docs
> Added utilities to debug protobuf conformance tests

- compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcDeclarationScanner.kt
- compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcIrContext.kt
- compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/RpcStubGenerator.kt
- compiler-plugin/compiler-plugin-backend/src/main/kotlin/kotlinx/rpc/codegen/extension/ServiceDeclaration.kt
- compiler-plugin/compiler-plugin-k2/src/main/kotlin/kotlinx/rpc/codegen/checkers/FirRpcStrictModeClassChecker.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/Status.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/annotations/Grpc.kt
- grpc/grpc-core/src/commonMain/kotlin/kotlinx/rpc/grpc/internal/suspendClientCalls.kt
- grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/CoreClientTest.kt
- grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/RawClientTest.kt
- grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/proto/GrpcProtoTest.kt
- grpc/grpc-core/src/commonTest/kotlin/kotlinx/rpc/grpc/test/proto/JavaPackageOptionTest.kt
- grpc/grpc-core/src/commonTest/proto/echo_grpc.proto
- grpc/grpc-core/src/commonTest/proto/helloworld_grpc.proto
- grpc/grpc-core/src/commonTest/proto/with_java_pkg_grpc.proto
- grpc/grpc-core/src/jvmMain/kotlin/kotlinx/rpc/grpc/Status.jvm.kt
- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/Status.native.kt
- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeClientCall.kt
- grpc/grpc-core/src/nativeTest/kotlin/kotlinx/rpc/grpc/internal/CoreTest.kt
- protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
- tests/compiler-plugin-tests/src/main/kotlin/kotlinx/rpc/codegen/test/Grpc.kt
- tests/compiler-plugin-tests/src/testData/box/grpc.fir.ir.txt
- tests/compiler-plugin-tests/src/testData/box/grpc.fir.txt
- tests/compiler-plugin-tests/src/testData/box/grpc.kt
**Subsystem**
gRPC
Currently the generated gRPC service name in the descriptor is just the simple names of the Kotlin interface. However, in gRPC a service name is structured as `<proto-package>.<name>`.
Additionally, the stub generator had no information about the `proto-package` set in the proto file, which is required to generate the correct service name. 
**Solution**
This PR adds the `protoPackage` argument to the `@Grpc` annotation. The service interface generator will set it if the `package` property is set in the proto file. 
This argument is then used by the service stub generator to obtain the proto package name.
To test this, the JavaPackageOptionTest was added, as well as an additional service interface in the compiler plugin tests.
Additionally, this …
> grpc: Fix service names in the generated descriptor

- .github/workflows/protobuf-conformance.yml
- protobuf/protobuf-core/src/commonMain/kotlin/kotlinx/rpc/protobuf/internal/ProtobufException.kt
- protobuf/protobuf-core/src/commonTest/proto/test_map.proto
- protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/model.kt
- protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
- tests/protobuf-conformance/build.gradle.kts
- tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/TestMessagesEdition2023.kt
- tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/edition2023/_rpc_internal/TestMessagesEdition2023.kt
- tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/TestMessagesProto2Editions.kt
- tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/editions/proto2/_rpc_internal/TestMessagesProto2Editions.kt
- tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/TestMessagesProto2.kt
- tests/protobuf-conformance/src/main/generated-code/kotlin-multiplatform/com/google/protobuf_test_messages/proto2/_rpc_internal/TestMessagesProto2.kt
- tests/protobuf-conformance/src/main/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceClient.kt
- tests/protobuf-conformance/src/test/kotlin/kotlinx/rpc/protoc/gen/test/ConformanceTest.kt
**Subsystem**
Protobuf
Proto2 conformance tests didn't compile and only proto3 and proto3 editions tests were activated.
**Solution**
This PR fixes all compilation errors and activate all conformance tests.
Additionally the `ConformanceTest` test runner now excludes all JSON related tests, as JSON is currently not supported.
The current conformance results are (JSON tests excluded):
```
=== Conformance Test Results (filtered) ===
Total baseline tests (filtered):   2805
[+] Passed tests:                  2790
[-] Failed tests:                  15
```
The 15 failing tests are:
1. Missing unknown fields in response message (we currently always skip unknown fields)
```
FAILED: 'Required.Proto2.ProtobufInput.UnknownOrdering.ProtobufOutput' with: Unknown field mismatch …
```
> protobuf: Enable all conformance tests

- grpc/grpc-core/src/nativeMain/kotlin/kotlinx/rpc/grpc/internal/NativeServerCall.kt
**Subsystem**
gRPC/Native
Native gRPC server was only sending a single message during server side streaming.
**Solution**
The `DeferredCallListener` missed the `onReady()` implementation.
> grpc: Fix onReady() listener delegation (KRPC-220)

- docs/environment.md
- gradle-conventions/src/main/kotlin/util/tasks/npm.kt
- kotlin-js-store/wasm/yarn.lock
- kotlin-js-store/yarn.lock
- krpc/krpc-client/src/commonMain/kotlin/kotlinx/rpc/krpc/client/KrpcClient.kt
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/KrpcConnector.kt
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/KrpcEndpoint.kt
- krpc/krpc-core/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/KrpcReceiveHandler.kt
- krpc/krpc-ktor/krpc-ktor-core/src/jvmTest/kotlin/kotlinx/rpc/krpc/ktor/KtorTransportTest.kt
- krpc/krpc-logging/src/commonMain/kotlin/kotlinx/rpc/krpc/internal/logging/RpcInternalCommonLogger.kt
- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/KrpcServer.kt
- krpc/krpc-server/src/commonMain/kotlin/kotlinx/rpc/krpc/server/internal/KrpcServerService.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/BackPressureTest.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationService.kt
- krpc/krpc-test/src/commonTest/kotlin/kotlinx/rpc/krpc/test/cancellation/CancellationTest.kt
- tests/compiler-plugin-tests/src/testData/box/customParameterTypes.kt
- tests/compiler-plugin-tests/src/testData/box/flowParameter.kt
- tests/compiler-plugin-tests/src/testData/box/multiModule.kt
- tests/compiler-plugin-tests/src/testData/box/simple.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/checkedAnnotation.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/rpcChecked.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/rpcService.kt
- tests/compiler-plugin-tests/src/testData/diagnostics/strictMode.kt
- tests/krpc-protocol-compatibility-tests/src/test/kotlin/kotlinx/rpc/krpc/test/compat/KrpcProtocolCompatibilityTestsBase.kt
- versions-root/libs.versions.toml
**Subsystem**
Tests
Ktor was lacking closure tests for transport
> Added Ktor closure tests and Cancellation tests, + minor fixes 

- docs/pages/kotlinx-rpc/rpc.tree
- docs/pages/kotlinx-rpc/topics/0-10-0.topic
- docs/pages/kotlinx-rpc/topics/configuration.topic
- docs/pages/kotlinx-rpc/topics/krpc-ktor.topic
> Added docs for release

- grpc/grpc-core/src/commonTest/proto/options.proto
- protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/AModelToKotlinCommonGenerator.kt
- protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/CodeGenerator.kt
- protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/codeRequestToModel.kt
- protoc-gen/common/src/main/kotlin/kotlinx/rpc/protoc/gen/core/model/model.kt
- protoc-gen/grpc/src/main/kotlin/kotlinx/rpc/protoc/gen/grpc/ModelToGrpcKotlinCommonGenerator.kt
- protoc-gen/protobuf/src/main/kotlin/kotlinx/rpc/protoc/gen/ModelToProtobufKotlinCommonGenerator.kt
**Subsystem**
Protoc-gen
Protobuf have deprecated options for different declarations
**Solution**
Generate `@Deprecated` annotation for them
> Support deprecated option in PB
